services:
  app:
    build: .
    container_name: haberes.app
    restart: unless-stopped
    environment:
      - DB_HOST=${DB_HOST}
      - DEBUG=${DEBUG}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
    volumes:
      - static_volume:/code/staticfiles
    expose:
      - 8000
    networks:
      - proxy

  nginx:
    build: ./nginx
    restart: unless-stopped
    container_name: haberes.nginx
    volumes:
      - static_volume:/code/staticfiles
    expose:
      - 80
    depends_on:
      - app
    networks:
      - proxy

volumes:
  static_volume:

networks:
  proxy:
    external: true
