services:
  app:
    build: .
    restart: unless-stopped
    volumes:
      - static_volume:/code/staticfiles
    expose:
      - 8000

  nginx:
    build: ./nginx
    restart: unless-stopped
    volumes:
      - static_volume:/code/staticfiles
    expose:
      - 80
    depends_on:
      - app

volumes:
  static_volume:
