# Generated by Django 3.1.5 on 2021-05-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='condicion',
            field=models.PositiveIntegerField(default=1, verbose_name='CONDICIÓN'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='nro_hijos',
            field=models.PositiveIntegerField(default=0, verbose_name='NÚMERO DE HIJOS'),
        ),
    ]
