# Generated by Django 3.1.5 on 2021-05-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0002_auto_20210512_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='condicion',
        ),
    ]
