# Generated by Django 3.1.5 on 2021-05-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0003_remove_trabajador_condicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
