# Generated by Django 3.1.5 on 2021-05-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiparch', models.PositiveIntegerField(verbose_name='TIPARCH')),
                ('codcon', models.PositiveIntegerField(verbose_name='CODCON')),
                ('descon', models.CharField(max_length=100, verbose_name='DESCON')),
                ('abrcon', models.CharField(max_length=50, verbose_name='ABRCON')),
                ('modifi', models.CharField(blank=True, max_length=2, null=True, verbose_name='MODIFI')),
                ('descon1', models.CharField(blank=True, max_length=50, null=True, verbose_name='DESCON1')),
                ('mes', models.PositiveIntegerField(verbose_name='MES')),
                ('anio', models.PositiveIntegerField(verbose_name='AÑO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Concepto',
                'verbose_name_plural': 'Conceptos',
                'ordering': ['codcon'],
            },
        ),
    ]
