# Generated by Django 3.1.5 on 2021-05-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepto', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='concepto',
            unique_together={('tiparch', 'codcon', 'mes', 'anio')},
        ),
    ]
