# Generated by Django 3.1.5 on 2021-05-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepto', '0003_auto_20210511_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concepto',
            options={'ordering': ['codcon', 'mes', 'anio'], 'verbose_name': 'Concepto', 'verbose_name_plural': 'Conceptos'},
        ),
    ]
