# Generated by Django 3.1.5 on 2021-05-31 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepto', '0004_auto_20210512_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concepto',
            options={'ordering': ['codcon', 'mes', 'anios'], 'verbose_name': 'Concepto', 'verbose_name_plural': 'Conceptos'},
        ),
        migrations.RenameField(
            model_name='concepto',
            old_name='anio',
            new_name='anios',
        ),
        migrations.AlterUniqueTogether(
            name='concepto',
            unique_together={('tiparch', 'codcon', 'mes', 'anios')},
        ),
    ]
