# Generated by Django 3.1.5 on 2021-05-31 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constancia', '0004_auto_20210524_1417'),
        ('concepto', '0005_auto_20210531_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concepto',
            options={'ordering': ['codcon', 'mes', 'anio'], 'verbose_name': 'Concepto', 'verbose_name_plural': 'Conceptos'},
        ),
        migrations.AddField(
            model_name='concepto',
            name='anio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='constancia.anio'),
        ),
        migrations.AlterUniqueTogether(
            name='concepto',
            unique_together={('tiparch', 'codcon', 'mes', 'anio')},
        ),
        migrations.RemoveField(
            model_name='concepto',
            name='anios',
        ),
    ]
