# Generated by Django 3.1.5 on 2021-05-18 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='type',
        ),
    ]
