# Generated by Django 3.1.5 on 2021-05-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPlanilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_pla', models.PositiveIntegerField(verbose_name='T_PLA')),
                ('des_pla', models.CharField(max_length=250, verbose_name='DES_PLA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo planilla',
                'verbose_name_plural': 'Tipos de planillas',
                'ordering': ['t_pla'],
            },
        ),
    ]
