# Generated by Django 3.1.5 on 2021-05-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoplanilla',
            name='t_pla',
            field=models.PositiveIntegerField(unique=True, verbose_name='T_PLA'),
        ),
    ]
