# Generated by Django 3.1.5 on 2021-06-24 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(max_length=5, verbose_name='Año')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Año',
                'verbose_name_plural': 'Años',
            },
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=850, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
            },
        ),
        migrations.CreateModel(
            name='EntidadEjecutora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=850, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entidad Ejecutora',
                'verbose_name_plural': 'Entidades Ejecutoras',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('apellidos_nombres', models.CharField(max_length=130, verbose_name='Apellidos y nombres')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('plaza', models.CharField(max_length=10, unique=True, verbose_name='Plaza')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('tipo', models.PositiveIntegerField(choices=[(1, 'NOMB. PROFESIONAL'), (2, 'NOMB. ADMINISTR.')], default=1)),
                ('nombres', models.CharField(blank=True, max_length=130, null=True, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(blank=True, max_length=130, null=True, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=130, null=True, verbose_name='Apellido materno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depedencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remuneracion.dependencia')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
            },
        ),
        migrations.CreateModel(
            name='Remuneracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingresos_remu_v_p', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='REMU/V.P.')),
                ('ingresos_otras_ue', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='OTRAS UE')),
                ('ingresos_otros', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='OTROS')),
                ('ingresos_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='TOTAL')),
                ('retencion_efectuar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='RETENCION X EFECTUAR')),
                ('retencion_remu_v_p', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='REMU/V.P.')),
                ('retencion_adicional', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ADICIONAL')),
                ('retencion_otros', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='OTROS')),
                ('retencion_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='TOTAL')),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='TOTAL A PAGAR O DEVOLVER')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remuneracion.anio')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remuneracion.trabajador')),
            ],
            options={
                'verbose_name': 'Remuneracion',
                'verbose_name_plural': 'Remuneraciones',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleRemuneracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField(choices=[(1, 'ENERO'), (2, 'FEBRERO'), (3, 'MARZO'), (4, 'ABRIL'), (5, 'MAYO'), (6, 'JUNIO'), (7, 'JULIO'), (8, 'AGOSTO'), (9, 'SEPTIEMBRE'), (10, 'OCTUBRE'), (11, 'NOVIEMBRE'), (12, 'DICIEMBRE')], default=1, verbose_name='MES')),
                ('ingresos_remu_v_p', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='REMU/V.P.')),
                ('ingresos_otras_ue', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='OTRAS UE')),
                ('ingresos_otros', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='OTROS')),
                ('ingresos_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='TOTAL')),
                ('retencion_efectuar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='RETENCION X EFECTUAR')),
                ('retencion_remu_v_p', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='REMU/V.P.')),
                ('retencion_adicional', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ADICIONAL')),
                ('retencion_otros', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='OTROS')),
                ('retencion_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='TOTAL')),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='TOTAL A PAGAR O DEVOLVER')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remuneracion.anio')),
                ('remuneracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='remuneracion.remuneracion')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remuneracion.trabajador')),
            ],
            options={
                'verbose_name': 'Detalle Remuneracion',
                'verbose_name_plural': 'Detalles Remuneracione',
                'ordering': ['mes'],
            },
        ),
        migrations.AddField(
            model_name='dependencia',
            name='entidad_ejecutora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remuneracion.entidadejecutora'),
        ),
    ]
