# Generated by Django 3.1.5 on 2021-05-12 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajador', '0003_remove_trabajador_condicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(max_length=5, verbose_name='Año')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Año',
                'verbose_name_plural': 'Años',
            },
        ),
        migrations.CreateModel(
            name='Constancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constancia.anio')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajador.trabajador')),
            ],
            options={
                'verbose_name': 'Constancia',
                'verbose_name_plural': 'Constacia',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ConstanciaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField(choices=[(1, 'ENERO'), (2, 'FEBRERO'), (3, 'MARZO'), (4, 'ABRIL'), (5, 'MAYO'), (6, 'JUNIO'), (7, 'JULIO'), (8, 'AGOSTO'), (9, 'SEPTIEMBRE'), (10, 'OCTUBRE'), (11, 'NOVIEMBRE'), (12, 'DICIEMBRE')], default=1, verbose_name='MES')),
                ('codeje', models.CharField(blank=True, max_length=50, null=True, verbose_name='CODEJE')),
                ('codfun', models.CharField(blank=True, max_length=50, null=True, verbose_name='CODFUN')),
                ('codpro', models.CharField(blank=True, max_length=50, null=True, verbose_name='CODPRO')),
                ('codsud', models.CharField(blank=True, max_length=50, null=True, verbose_name='CODSUB')),
                ('tipopla', models.CharField(blank=True, max_length=50, null=True, verbose_name='TIPOPLA')),
                ('progsub', models.CharField(blank=True, max_length=50, null=True, verbose_name='PROGSUB')),
                ('codest', models.CharField(blank=True, max_length=50, null=True, verbose_name='CODEST')),
                ('codcom', models.CharField(blank=True, max_length=50, null=True, verbose_name='CODCOM')),
                ('serv', models.CharField(blank=True, max_length=50, null=True, verbose_name='SERV')),
                ('codcar', models.CharField(blank=True, max_length=50, null=True, verbose_name='CODCAR')),
                ('codniv', models.CharField(blank=True, max_length=50, null=True, verbose_name='CODNIV')),
                ('concepto', models.CharField(max_length=4, verbose_name='Conceptp')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constancia.anio')),
                ('constancia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constancia.constancia')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajador.trabajador')),
            ],
            options={
                'verbose_name': 'Contancia Detalle',
                'verbose_name_plural': 'Contancias Detalle',
                'ordering': ['mes'],
            },
        ),
    ]
