# Generated by Django 3.1.5 on 2021-05-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constancia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constanciadetalle',
            options={'ordering': ['mes', 'concepto'], 'verbose_name': 'Contancia Detalle', 'verbose_name_plural': 'Contancias Detalle'},
        ),
        migrations.AlterField(
            model_name='constanciadetalle',
            name='concepto',
            field=models.CharField(max_length=4, verbose_name='Concepto'),
        ),
    ]
