# Generated by Django 3.1.5 on 2021-05-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constancia', '0002_auto_20210513_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constancia',
            options={'ordering': ['trabajador__nombre_completo'], 'verbose_name': 'Constancia', 'verbose_name_plural': 'Constacia'},
        ),
        migrations.AlterField(
            model_name='anio',
            name='anio',
            field=models.PositiveIntegerField(verbose_name='Año'),
        ),
    ]
