# Generated by Django 3.1.5 on 2021-05-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constancia', '0003_auto_20210524_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='constancia',
            name='codcar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CODCAR'),
        ),
        migrations.AddField(
            model_name='constancia',
            name='codest',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CODEST'),
        ),
        migrations.AddField(
            model_name='constancia',
            name='nivel',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='NIVEL'),
        ),
        migrations.AddField(
            model_name='constancia',
            name='plaza',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='PLAZA'),
        ),
    ]
