# Generated by Django 3.1.5 on 2021-06-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0005_trabajador_nombre_completo'),
        ('constancia', '0004_auto_20210524_1417'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='constancia',
            unique_together={('trabajador', 'plaza', 'anio')},
        ),
    ]
