# Generated by Django 3.1.5 on 2021-05-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codant', models.PositiveIntegerField(verbose_name='CODANT')),
                ('codcar', models.PositiveIntegerField(unique=True, verbose_name='CODCAR')),
                ('descar', models.CharField(max_length=250, verbose_name='DESCAR')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['codcar'],
            },
        ),
    ]
