# Generated by Django 3.1.5 on 2021-05-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='codant',
            field=models.PositiveIntegerField(blank=True, max_length=4, null=True, verbose_name='CODANT'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='codcar',
            field=models.CharField(max_length=4, unique=True, verbose_name='CODCAR'),
        ),
    ]
