# Generated by Django 3.1.5 on 2021-05-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_auto_20210511_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='codant',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='CODANT'),
        ),
    ]
