# Generated by Django 3.1.5 on 2021-05-31 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constancia', '0004_auto_20210524_1417'),
        ('cargo', '0003_auto_20210511_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='anio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='constancia.anio'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='codcar',
            field=models.CharField(max_length=4, verbose_name='CODCAR'),
        ),
        migrations.AlterUniqueTogether(
            name='cargo',
            unique_together={('codcar', 'anio')},
        ),
    ]
