# Generated by Django 3.1.5 on 2021-05-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progsub', models.PositiveIntegerField(verbose_name='PROGSUB')),
                ('codest', models.PositiveIntegerField(unique=True, verbose_name='CODEST')),
                ('desest', models.CharField(max_length=250, verbose_name='DESEST')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Establecimiento',
                'verbose_name_plural': 'Tipos de planillas',
                'ordering': ['desest'],
            },
        ),
    ]
