# Generated by Django 3.1.5 on 2021-05-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='establecimiento',
            options={'ordering': ['desest'], 'verbose_name': 'Establecimiento', 'verbose_name_plural': 'Establecimientos'},
        ),
    ]
