# Generated by Django 3.1.5 on 2021-05-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0002_auto_20210511_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='codest',
            field=models.CharField(max_length=9, unique=True, verbose_name='CODEST'),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='progsub',
            field=models.CharField(max_length=5, verbose_name='PROGSUB'),
        ),
    ]
