# Generated by Django 3.1.5 on 2021-05-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0003_auto_20210511_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='codest',
            field=models.CharField(max_length=9, verbose_name='CODEST'),
        ),
        migrations.AlterUniqueTogether(
            name='establecimiento',
            unique_together={('progsub', 'codest')},
        ),
    ]
