# Generated by Django 3.1.5 on 2021-05-31 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constancia', '0004_auto_20210524_1417'),
        ('establecimiento', '0004_auto_20210511_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='anio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='constancia.anio'),
        ),
        migrations.AlterUniqueTogether(
            name='establecimiento',
            unique_together={('progsub', 'codest', 'anio')},
        ),
    ]
